CREATE TABLE "main"."EquipmentType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "main"."Equipment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "equipmentTypeId" integer,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "specification" JSON
);

CREATE TABLE "main"."EquipmentLocation" (
  "equipmentId" integer,
  "generalLocation" main."wpGeneralLocation",
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50),
  "note" text
);

ALTER TABLE "main"."Equipment" ADD FOREIGN KEY ("equipmentTypeId") REFERENCES "main"."EquipmentType" ("id");

ALTER TABLE "main"."EquipmentLocation" ADD FOREIGN KEY ("equipmentId") REFERENCES "main"."Equipment" ("id");

