-- ALTER TABLE "main"."WaferTypeExtras"
-- RENAME TO "WaferTypeMap";
--
-- ALTER TABLE "main"."WaferTypeMap"
-- DROP COLUMN "imageBase64String";
--
-- ALTER TABLE "main"."WaferTypeMap"
-- ALTER COLUMN "waferMap"
-- SET
-- NOT NULL;
--
-- CREATE TABLE "main"."WaferTypeImage" (
-- "waferTypeId" integer NOT NULL,
-- "imageBase64String" text NOT NULL
-- );
--
-- ALTER TABLE "main"."WaferTypeImage" ADD FOREIGN KEY ("waferTypeId") REFERENCES
-- "main"."WaferType" ("id");
--
-- ALTER TABLE "main"."WaferType" ADD CONSTRAINT "unique_name" UNIQUE ("name");
--
-- ALTER TABLE "main"."WaferType" ADD CONSTRAINT "unique_engineeringRun" UNIQUE
-- ("engineeringRun");
--
-- ALTER TABLE "main"."WaferTypeMap" ADD CONSTRAINT "unique_waferTypeId" UNIQUE
-- ("waferTypeId");
-- INSERT INTO
-- "main"."WaferTypeExtras" ("waferTypeId", "waferMap")
-- SELECT
-- id,
-- "waferMap"
-- FROM
-- "main"."WaferType";
-- ALTER TABLE "main"."WaferType"
-- DROP COLUMN "waferMap" CASCADE;

