CREATE TABLE "main"."MOSAIXTestList" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "main"."MOSAIXTestConfiguration" (
  "testId" integer,
  "version" integer,
  "baseversion" integer,
  "configJSON" JSON,
  "date" date DEFAULT (CURRENDATE),
  "notes" text
);

ALTER TABLE "main"."MOSAIXTestConfiguration" ADD FOREIGN KEY ("testId") REFERENCES "main"."MOSAIXTestList" ("id");

