CREATE SCHEMA "main";

CREATE TYPE "main"."asicFamilyType" AS ENUM (
  'MOST',
  'MOSS',
  'BABYMOSS',
  'BABYMOST',
  'NKF7',
  'MOSAIX',
  'BABYMOSAIX',
  'LAS',
  'AncMPW1',
  'AncMPW2',
  'AncMPW3',
  'AncBrain',
  'AncASIC',
  'CE65_V1CG_15U_SQ',
  'CE65_V2CG_15U_SQ',
  'CE65_V2CG_18U_SQ',
  'CE65_V2CG_18U_HSQ',
  'CE65_V2CG_22U5_SQ',
  'CE65_V2CG_22U5_HSQ',
  'CE65_V2CN_15U_SQ',
  'CE65_V2CN_18U_SQ',
  'CE65_V2CN_18U_HSQ',
  'CE65_V2CN_22U5_SQ',
  'CE65_V2CN_22U5_HSQ',
  'AO10P',
  'AO10',
  'AO10B',
  'S',
  'DESY',
  'NONAME1',
  'CE65_V1CN_15U_SQ',
  'NONAME2',
  'CE65_V1CB_15U_SQ',
  'dPTSN',
  'dPTS',
  'AF15P',
  'AF15B',
  'AF15',
  'RAL_TXRX_ER1',
  'TTS_5',
  'TTS_4',
  'CE65_V2CB_15U_SQ',
  'CE65_V2CB_22U5_SQ',
  'CE65_V2CB_18U_HSQ',
  'CE65_V2CB_22U5_HSQ',
  'CE65_V2CB_18U_SQ',
  'NKF5',
  'NKF6',
  'NONAME5',
  'SEU_2_INFN_BAR_GDR',
  'SEU_1_INFN_BAR_GDR',
  'TTS_3',
  'TTS_2',
  'TTS_1',
  'ER2_APTS_OA_10_G',
  'ER2_APTS_OA_10_P3',
  'ER2_APTS_OA_10_P4',
  'ER2_APTS_OA_10_P5',
  'ER2_APTS_SF_10_G',
  'ER2_APTS_SF_10_P3',
  'ER2_APTS_SF_10_P4',
  'ER2_APTS_SF_10_P5',
  'ER2_APTS_SF_12_G',
  'ER2_APTS_SF_15_S',
  'ER2_APTS_SF_15_M',
  'ER2_APTS_SF_15_G',
  'ER2_APTS_SF_30_G',
  'ER2_APTS_SF_40_G',
  'ER2_APTS_SF_50_G',
  'ER2_APTS_SF_50_NW',
  'ER2_APTS_SF_MOSAIX',
  'ER2_BNL_ADC',
  'ER2_BNL_DATATR',
  'ER2_BG_TMON',
  'ER2_DPTS',
  'ER2_DPTS_P3',
  'ER2_DPTS_P5',
  'ER2_NAPA_v2',
  'ER2_RING_OSC_v1',
  'ER2_RING_OSC_v2',
  'ER2_SEU3',
  'ER2_SERIALIZER',
  'ER2_SPARC',
  'ER2_TDC_HEID',
  'ER2_TTS1',
  'ER2_TTS2'
);

CREATE TYPE "main"."asicQuality" AS ENUM (
  'MechanicallyDamaged',
  'MechanicallyInteger',
  'CoveredByGreenLayer'
);

CREATE TYPE "main"."blockType" AS ENUM (
  'AncMPW1_SLDO',
  'AncMPW1_NVBG',
  'AncMPW1_CML_TRANSCEIVER'
);

CREATE TYPE "main"."dutType" AS ENUM (
  'MOSAIX',
  'BABYMOSAIX',
  'AncMPW1_SLDO',
  'AncMPW1_NVBG',
  'AncMPW1_CML_TRANSCEIVER'
);

CREATE TYPE "main"."engineeringRun" AS ENUM (
  'ER1',
  'ER2',
  'ER3',
  'LAS1',
  'AncMPW1'
);

CREATE TYPE "main"."foundryName" AS ENUM (
  'TowerSemiconductor',
  'Xfab'
);

CREATE TYPE "main"."pcLocation" AS ENUM (
  'CERN',
  'Prague',
  'LosAlamos',
  'BNL',
  'RAL'
);

CREATE TYPE "main"."pcModel" AS ENUM (
  'NKF7-TS3500-CABLEOUT-MLO(EVS-P)',
  'MosaixLeft',
  'MosaixRight',
  'LAS',
  'BabyMOSS',
  'Ancillary'
);

CREATE TYPE "main"."pcName" AS ENUM (
  'NKF7_MPI',
  'BabyMOSS_Korea',
  'Mosaix_Korea'
);

CREATE TYPE "main"."pcType" AS ENUM (
  'Vertical',
  'Cantilever'
);

CREATE TYPE "main"."pcVendor" AS ENUM (
  'MPI',
  'Korea',
  'Synergie',
  'FormFactorPC'
);

CREATE TYPE "main"."waferTech" AS ENUM (
  'TPSCo65',
  'Xfab110'
);

CREATE TYPE "main"."waferInMachineStatus" AS ENUM (
  'Loaded',
  'Unloaded'
);

CREATE TYPE "main"."waferMapOrientation" AS ENUM (
  'North',
  'South',
  'East',
  'West'
);

CREATE TYPE "main"."wpConnectionType" AS ENUM (
  'TCPIP',
  'GPIB',
  'RS232',
  'USB',
  'Ethernet',
  'Modbus',
  'LAN'
);

CREATE TYPE "main"."wpGeneralLocation" AS ENUM (
  'CERN',
  'CERN_186_R_E10',
  'Prague',
  'LosAlamos',
  'BNL',
  'RAL',
  'Darsburry',
  'Brunel',
  'Birmingham',
  'Liverpool',
  'LBL'
);

CREATE TYPE "main"."wpSwType" AS ENUM (
  'Sentio',
  'VeloxCascade'
);

CREATE TYPE "main"."wpVendor" AS ENUM (
  'MPI',
  'CascadeMicrotech',
  'FormFactor'
);

CREATE TABLE "main"."WaferType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "engineeringRun" main."engineeringRun" UNIQUE NOT NULL,
  "foundry" main."foundryName" NOT NULL,
  "technology" main."waferTech" NOT NULL
);

CREATE TABLE "main"."WaferTypeMap" (
  "waferTypeId" integer PRIMARY KEY,
  "waferMap" JSON NOT NULL
);

CREATE TABLE "main"."WaferTypeImage" (
  "waferTypeId" integer PRIMARY KEY,
  "imageBase64String" text NOT NULL
);

CREATE TABLE "main"."Wafer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "waferTypeId" integer NOT NULL,
  "serialNumber" varchar(50) UNIQUE NOT NULL,
  "batchNumber" integer NOT NULL,
  "thinningDate" date,
  "dicingDate" date,
  "productionDate" date,
  "generalLocation" main."wpGeneralLocation"
);

CREATE TABLE "main"."WaferLocation" (
  "waferId" integer NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50),
  "note" text
);

CREATE TABLE "main"."Asic" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "waferId" integer NOT NULL,
  "serialNumber" varchar(50) UNIQUE NOT NULL,
  "familyType" main."asicFamilyType" NOT NULL,
  "waferMapPosition" varchar(50) NOT NULL,
  "quality" main."asicQuality" NOT NULL
);

CREATE TABLE "main"."Chip" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asicId" integer NOT NULL,
  "serialNumber" varchar(50) UNIQUE NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL
);

CREATE TABLE "main"."ChipLocation" (
  "chipId" integer NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50),
  "note" text
);

CREATE TABLE "main"."Block" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chipId" integer NOT NULL,
  "blockType" main."blockType" NOT NULL,
  "serialNumber" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "main"."AsicFamilyTypeBlockList" (
  "asicFamilyType" main."asicFamilyType",
  "blockType" main."blockType",
  PRIMARY KEY ("asicFamilyType", "blockType")
);

CREATE TABLE "main"."ProbeCard" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "serialNumber" varchar(50) UNIQUE NOT NULL,
  "vendor" main."pcVendor" NOT NULL,
  "name" main."pcName" UNIQUE NOT NULL,
  "model" main."pcModel" NOT NULL,
  "version" integer NOT NULL,
  "arrivalDate" date NOT NULL,
  "location" main."pcLocation" NOT NULL,
  "type" main."pcType" NOT NULL,
  "vendorCleaningInterval" integer NOT NULL
);

CREATE TABLE "main"."ProbeCardFamilyType" (
  "probeCardId" integer NOT NULL,
  "asicFamilyType" main."asicFamilyType" NOT NULL,
  PRIMARY KEY ("probeCardId", "asicFamilyType")
);

CREATE TABLE "main"."WaferProbeMachine" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "serialNumber" varchar(50) UNIQUE NOT NULL,
  "name" varchar(50) UNIQUE NOT NULL,
  "hostName" varchar(200) NOT NULL,
  "connectionType" main."wpConnectionType" NOT NULL,
  "connectionPort" integer NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "software" main."wpSwType" NOT NULL,
  "swVersion" varchar(50) NOT NULL,
  "vendor" main."wpVendor" NOT NULL,
  "loadedWaferId" integer,
  "loadedWaferOrientation" main."waferMapOrientation",
  "installedProbeCardId" integer,
  "installedProbeCardOrientation" main."waferMapOrientation"
);

CREATE TABLE "main"."WaferLoadedInMachine" (
  "machineId" integer NOT NULL,
  "waferId" integer NOT NULL,
  "orientation" main."waferMapOrientation",
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50),
  "status" main."waferInMachineStatus"
);

CREATE TABLE "main"."ProbeCardInstalledInMachine" (
  "machineId" integer NOT NULL,
  "probeCardId" integer NOT NULL,
  "orientation" main."waferMapOrientation",
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50)
);

CREATE TABLE "main"."WaferProbeProject" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wpMachineId" integer NOT NULL,
  "waferTypeId" integer NOT NULL,
  "asicFamilyType" main."asicFamilyType",
  "orientation" main."waferMapOrientation",
  "name" varchar(100) UNIQUE NOT NULL,
  "alignmentDie" varchar(100),
  "homeDie" varchar(100),
  "local2GlobalMap" JSON
);

CREATE TABLE "main"."EquipmentType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "main"."Equipment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "equipmentTypeId" integer NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "specification" JSON
);

CREATE TABLE "main"."EquipmentLocation" (
  "equipmentId" integer NOT NULL,
  "generalLocation" main."wpGeneralLocation" NOT NULL,
  "date" date DEFAULT (CURRENT_DATE),
  "username" varchar(50),
  "note" text
);

CREATE TABLE "main"."SvtTestSetup" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "generalLocation" main."wpGeneralLocation"
);

CREATE TABLE "main"."SvtTestSetupDefaultConfig" (
  "setupId" integer PRIMARY KEY,
  "defaultConfigId" integer
);

CREATE TABLE "main"."SvtTestSetupEquipList" (
  "setupId" integer,
  "equipId" integer,
  PRIMARY KEY ("setupId", "equipId")
);

CREATE TABLE "main"."SvtTestSetupConfig" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setupId" integer NOT NULL,
  "name" varchar(100) UNIQUE NOT NULL,
  "note" text,
  "configBody" JSON NOT NULL,
  "createdAt" date DEFAULT (CURRENT_DATE)
);

CREATE TABLE "main"."SvtTestType" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "main"."SvtTestTypeDUTTypeList" (
  "dutType" main."dutType" NOT NULL,
  "testTypeId" integer NOT NULL,
  PRIMARY KEY ("dutType", "testTypeId")
);

CREATE TABLE "main"."SvtTestTypeConfig" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "testTypeId" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "note" text,
  "configBody" JSON NOT NULL,
  "createdAt" date DEFAULT (CURRENT_DATE)
);

CREATE TABLE "main"."SvtTestTemplate" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dutType" main."dutType",
  "testTypeConfigId" integer,
  "isEnabled" bool DEFAULT true
);

CREATE TABLE "main"."SvtTestList" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "testTypeConfigId" integer NOT NULL,
  "testSetupConfigId" integer,
  "createsAt" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "startedAt" timestamp,
  "finishedAt" timestamp,
  "pathToResult" text,
  "testResultStatus" varchar(50)
);

CREATE TABLE "main"."SvtAsicTestList" (
  "asicId" integer,
  "testId" integer,
  PRIMARY KEY ("asicId", "testId")
);

CREATE TABLE "main"."SvtChipTestList" (
  "chipId" integer,
  "testId" integer,
  PRIMARY KEY ("chipId", "testId")
);

CREATE TABLE "main"."SvtBlockTestList" (
  "blockId" integer,
  "testId" integer,
  PRIMARY KEY ("blockId", "testId")
);

CREATE UNIQUE INDEX ON "main"."SvtTestTypeConfig" ("testTypeId", "name");

CREATE UNIQUE INDEX ON "main"."SvtTestTemplate" ("dutType", "testTypeConfigId");

ALTER TABLE "main"."WaferTypeMap" ADD FOREIGN KEY ("waferTypeId") REFERENCES "main"."WaferType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferTypeImage" ADD FOREIGN KEY ("waferTypeId") REFERENCES "main"."WaferType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."Wafer" ADD FOREIGN KEY ("waferTypeId") REFERENCES "main"."WaferType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferLocation" ADD FOREIGN KEY ("waferId") REFERENCES "main"."Wafer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."Asic" ADD FOREIGN KEY ("waferId") REFERENCES "main"."Wafer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."Chip" ADD FOREIGN KEY ("asicId") REFERENCES "main"."Asic" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."ChipLocation" ADD FOREIGN KEY ("chipId") REFERENCES "main"."Chip" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."Block" ADD FOREIGN KEY ("chipId") REFERENCES "main"."Chip" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."ProbeCardFamilyType" ADD FOREIGN KEY ("probeCardId") REFERENCES "main"."ProbeCard" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferProbeMachine" ADD FOREIGN KEY ("loadedWaferId") REFERENCES "main"."Wafer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferProbeMachine" ADD FOREIGN KEY ("installedProbeCardId") REFERENCES "main"."ProbeCard" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferLoadedInMachine" ADD FOREIGN KEY ("machineId") REFERENCES "main"."WaferProbeMachine" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferLoadedInMachine" ADD FOREIGN KEY ("waferId") REFERENCES "main"."Wafer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."ProbeCardInstalledInMachine" ADD FOREIGN KEY ("machineId") REFERENCES "main"."WaferProbeMachine" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."ProbeCardInstalledInMachine" ADD FOREIGN KEY ("probeCardId") REFERENCES "main"."ProbeCard" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferProbeProject" ADD FOREIGN KEY ("wpMachineId") REFERENCES "main"."WaferProbeMachine" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."WaferProbeProject" ADD FOREIGN KEY ("waferTypeId") REFERENCES "main"."WaferType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."Equipment" ADD FOREIGN KEY ("equipmentTypeId") REFERENCES "main"."EquipmentType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."EquipmentLocation" ADD FOREIGN KEY ("equipmentId") REFERENCES "main"."Equipment" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestSetupDefaultConfig" ADD FOREIGN KEY ("setupId") REFERENCES "main"."SvtTestSetup" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestSetupDefaultConfig" ADD FOREIGN KEY ("defaultConfigId") REFERENCES "main"."SvtTestSetupConfig" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestSetupEquipList" ADD FOREIGN KEY ("setupId") REFERENCES "main"."SvtTestSetup" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestSetupEquipList" ADD FOREIGN KEY ("equipId") REFERENCES "main"."Equipment" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestSetupConfig" ADD FOREIGN KEY ("setupId") REFERENCES "main"."SvtTestSetup" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestTypeDUTTypeList" ADD FOREIGN KEY ("testTypeId") REFERENCES "main"."SvtTestType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestTypeConfig" ADD FOREIGN KEY ("testTypeId") REFERENCES "main"."SvtTestType" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestTemplate" ADD FOREIGN KEY ("testTypeConfigId") REFERENCES "main"."SvtTestTypeConfig" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtTestList" ADD FOREIGN KEY ("testTypeConfigId") REFERENCES "main"."SvtTestTypeConfig" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtAsicTestList" ADD FOREIGN KEY ("asicId") REFERENCES "main"."Asic" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtAsicTestList" ADD FOREIGN KEY ("testId") REFERENCES "main"."SvtTestList" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtChipTestList" ADD FOREIGN KEY ("chipId") REFERENCES "main"."Chip" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtChipTestList" ADD FOREIGN KEY ("testId") REFERENCES "main"."SvtTestList" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtBlockTestList" ADD FOREIGN KEY ("blockId") REFERENCES "main"."Block" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "main"."SvtBlockTestList" ADD FOREIGN KEY ("testId") REFERENCES "main"."SvtTestList" ("id") DEFERRABLE INITIALLY IMMEDIATE;
