-- INSERT INTO
-- main."SvtTestSetup" (name, "generalLocation")
-- VALUES
-- ('ts_mit', 'CERN_186_R_E10'),
-- ('analog_monitor_prober_mit', 'CERN_186_R_E10'),
-- ('sldo_ts_brunel', 'Brunel');
-- INSERT INTO
-- main."SvtTestSetupAsicFamilyTypeList" ("setupId", "asicFamilyType")
-- VALUES
-- (1, 'BABYMOSAIX'),
-- (1, 'MOSAIX'),
-- (3, 'AncMPW1');

